### ISSUE TITLE
Add time

### ISSUE THREAD

**Issue by johnef** [uxsolutions/bootstrap-datepicker#2047] opened 2016-10-29 12:37 UTC
### Expected behaviour
just add the icon for clock and add time

### Actual behaviour
Tell us what happens instead.

### Datepicker version used

Latest

### Example code

Jsfiddle example to reproduce the problem.

**Comment by Azaret** [comment] 2016-10-29 13:51
Duplicate of #29

**Closed by Azaret** 2016-10-29 13:51 UTC
