### ISSUE TITLE
[bug]click another elements hidden datepicker will hidden also

### ISSUE THREAD

**Issue by joebnb** [uxsolutions/bootstrap-datepicker#1366] opened 2015-04-11 04:12 UTC
```
<div class="alert alert-success">
    <div class="close">X</div>
    somenotify
</div>
<div id="datepicker"></div>
<script type="text/javascript">

    $('#datepicker').datepicker({
                format: "yyyy/mm/dd",
                weekStart: 0,
                //language: "zh-CN",
                todayHighlight: true
            });
</script>
```

if i click X to hidden alert,.date time will hidden...i dont konw why will cause this,i use it in  Embedded / inline model
i found here was a bug,i think it should determined did this works inline:

```
                [$(document), {
                    mousedown: $.proxy(function(e){
                        // Clicked outside the datepicker, hide it
                        if (!(
                            this.element.is(e.target) ||
                            this.element.find(e.target).length ||
                            this.picker.is(e.target) ||
                            this.picker.find(e.target).length
                        )){
                            //$(this.picker).hide();
                        }
                    }, this)
```

**Comment by joebnb** [comment] 2015-04-20 10:32
```
					mousedown: $.proxy(function(e){
						// Clicked outside the datepicker, hide it
						if (!(
							this.element.is(e.target) ||
							this.element.find(e.target).length ||
							this.picker.is(e.target) ||
							this.picker.find(e.target).length ||
							this.element.attr('data-module') != 'inline'
						)){
							$(this.picker).hide();
						}
```
i redit like this， and if i want make it inline，will add attributes data-module=“inline”

**Comment by joebnb** [comment] 2015-04-20 10:32
wish fix it in next update

**Comment by NeilWkz** [comment] 2015-05-12 15:44
+1 Joebnb
I've hit this bug also I'll clarify this here to make sure it's the same issue joebnb mentions above.

When the datepicker is being used in inline/embedded mode, it's hidden whenever another mousedown is called on another element on the page.

at first look Joe's fix seems to work.

**Comment by alvin0618** [comment] 2015-05-20 04:43
May I know why the example didn't hit the bug? the inline mode of datepicker is not hidden up.

http://eternicode.github.io/bootstrap-datepicker/?markup=embedded&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox

**Comment by alvin0618** [comment] 2015-05-21 01:50
Fixed, code should be like this
<code>

                mousedown: $.proxy(function(e){
                        // Clicked outside the datepicker, hide it
                        if (!(
                            this.element.is(e.target) ||
                            this.element.find(e.target).length ||
                            this.picker.is(e.target) ||
                            this.picker.find(e.target).length ||
                            this.isInline == true
                        )){
                            $(this.picker).hide();
                        }
                 }, this)
</code>

**Comment by razvanphp** [comment] 2015-05-26 18:40
@alvin0618 this bug appears in 1.4.1-dev, the example page has 1.4.1 stable.

I'm not sure what introduced this funny bug, should we create a pull request for it?

**Comment by acrobat** [comment] 2015-05-27 10:49
Yes please, if you have a fix create a PR for it. So the we can review it and check if the original problem (what was fixed in the currently broken code) is still fixed

**Comment by alvin0618** [comment] 2015-06-02 07:20
@razvanphp i downloaded the 1.5.0dev version, the problem is still there.

**Closed** 2020-08-12 03:27 UTC
