### ISSUE TITLE
Multiple months on the popup

### ISSUE THREAD

**Issue by ranji2612** [uxsolutions/bootstrap-datepicker#1052] opened 2014-08-25 20:20 UTC
Currently we are seeing only one month on the Calendar. It will be very useful if we can set an option to see multiple months. For instance if i want to see a 3 month calendar it would be very useful.

**Comment by jelhan** [comment] 2016-08-15 00:41
Duplicate of #1154

**Closed** 2016-10-20 21:55 UTC
