### ISSUE TITLE
How to show two months?

### ISSUE THREAD

**Issue by Viveksubramani** [uxsolutions/bootstrap-datepicker#983] opened 2014-06-16 07:08 UTC
How to show two months?

**Comment by Medvezhopok** [comment] 2015-06-18 07:32
+1

**Comment by HexDT** [comment] 2016-01-18 17:37
This would be very helpful !... wish I could help...

**Comment by BernieCook** [comment] 2016-03-18 12:39
+1

**Comment by MrGeneric** [comment] 2016-03-18 12:51
It's worth considering the date range picker I've linked below if you want the ability to display two months. It is relatively popular and under active development.

https://github.com/dangrossman/bootstrap-daterangepicker

**Comment by BernieCook** [comment] 2016-03-18 12:56
Thanks David. I did come across that but your existing datepicker has a lot
of features I need, less the displaying of multiple months when embedded.

That's okay I'll work around it.

Cheers for the prompt response.

Bernie

**Comment by MrGeneric** [comment] 2016-03-18 13:14
Hi Bernie, I'm only someone who follows this project, don't want to take credit for any of the hard work involved. Hope you can find or build something that works for you. 

All the best,
David

**Comment by jelhan** [comment] 2016-08-15 00:41
Duplicate of #1154

**Closed** 2016-10-20 21:57 UTC
Labels: feature-request

**Comment by Sridharsrivin** [comment] 2017-08-24 16:14
<script>
	$( function() {
		$( "#datepicker" ).datepicker({
			numberOfMonths: 2
		});
	} );
</script>

<p>Date: <input type="text" id="datepicker"></p>
