### ISSUE TITLE
Multiple calendar month view

### ISSUE THREAD

**Issue by leads** [uxsolutions/bootstrap-datepicker#1047] opened 2014-08-22 11:46 UTC
Hi. Has anyone forked this so it can show multiple months at the same time? Like: https://jqueryui.com/resources/demos/datepicker/multiple-calendars.html

Thanks

**Comment by jelhan** [comment] 2016-08-15 00:42
Duplicate of #1154

**Closed** 2016-10-20 21:58 UTC
