### ISSUE TITLE
Date range picker and manual date entering

### ISSUE THREAD

**Issue by r0x0r** [uxsolutions/bootstrap-datepicker#1817] opened 2016-03-03 09:51 UTC
When you enter a date manually with keyboard in a date range picker the value of the other picker gets updated immediately which leads to unintended effects. 

E.g. given a range picker with the following dates
15/01/2015 - 17/01/2016

If you edit the year of the end date and delete the last number, it automatically sets the start date to the year of 201, so the date range becomes 

15/01/201 - 17/01/201

Fixing the end date does not fix the start date, so you end up with 

15/01/201 - 17/01/2015

The js fiddle can be found here https://jsfiddle.net/ayszdoo1/

Is there any way to prevent this behaviour? Maybe debounce the update logic or something like that?

**Comment by emanuelbaruch** [comment] 2016-03-03 17:10
you could prevent this by removing these lines of code:

			else if (dates.length){
				// setting date by typing
				if (String(oldDates) !== String(this.dates))
					this._trigger('changeDate');
			}

**Comment by audacity76** [comment] 2016-03-14 09:05
there should be an option to prevent this behavior

**Comment by hebbet** [comment] 2016-03-14 12:27
if you want this, please either provide a PR or use the new reactions feature. Comments like +1, "i want this" etc. doesn't speed up development.

**Comment by r0x0r** [comment] 2016-03-15 12:52
I have solved this by commenting out this code on lines 1650-1660.

			if (new_date < this.dates[j]){
				// Date being moved earlier/left
				while (j >= 0 && new_date < this.dates[j]){
					this.pickers[j--].setUTCDate(new_date);
				}
			}
			else if (new_date > this.dates[k]){
				// Date being moved later/right
				while (k < l && new_date > this.dates[k]){
					this.pickers[k++].setUTCDate(new_date);
				}

The solution proposed above was unsatisfactory, because it suppresses changeDate events.

**Comment by samiraguiar** [comment] 2016-04-18 17:37
This is a duplicate of #721. A workaround is provided there.

**Comment by stof** [comment] 2016-08-23 10:58
This looks related to https://github.com/eternicode/bootstrap-datepicker/issues/1837

**Comment by julesbou** [comment] 2016-09-05 08:27
as @samiraguiar said, there's a solution without modifying the code, see  https://github.com/eternicode/bootstrap-datepicker/issues/721#issuecomment-86275874

**Comment by Azaret** [comment] 2016-10-28 17:37
PR #1891 is ongoing, hopefully be soon pushed in `1.7.0`.

**Closed by Azaret** 2016-10-28 17:37 UTC
Labels: is-bug, release-1.7.0

**Comment by amucino** [comment] 2017-01-19 14:08
I opened a new issue, but seems this is the same. Is this fixed in the latest version ?
