### ISSUE TITLE
Feature Request: Select Time Inline

### ISSUE THREAD

**Issue by danielbonnell** [uxsolutions/bootstrap-datepicker#1952] opened 2016-07-22 16:28 UTC
This is a feature request for an inline time selector similar (or exactly) like the one that [Buffer](https://buffer.com/) uses. Buffer's datepicker is a fork of this project but has not received a commit in several years. I'd like to use it for a project, but it lacks many of the customization options that this project now has. I have not seen any other Bootstrap datepicker plugins with an inline time selector.

**Comment by jelhan** [comment] 2016-08-18 17:20
[bootstrap-datetimepicker](https://eonasdan.github.io/bootstrap-datetimepicker/#inline) has a feature like this one.

**Comment by Azaret** [comment] 2016-10-29 13:51
Duplicate of #29

**Closed by Azaret** 2016-10-29 13:51 UTC
Labels: is-feature, release-next
